# Generated by Django 3.0.6 on 2020-07-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
