"""
Django settings for Bookwallah project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from celery.schedules import crontab
from django.conf.locale.en import formats as en_formats

en_formats.DATETIME_FORMAT = "d M Y H:i:s"


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mq6)-bqxzos%kgz)0rzu*--eu=y-4s^s(mg9s)t175^k8if!1q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ASGI_APPLICATION = "Bookwallah.asgi.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
ALLOWED_HOSTS = ['127.0.0.1']
#ALLOWED_HOSTS =  ['35.154.243.159','ec2-35-154-243-159.ap-south-1.compute.amazonaws.com','bookwallahdashboard.org','www.bookwallahdashboard.org']

IMPORT_EXPORT_USE_TRANSACTIONS = True
# # Application definition

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'bookwallahhr@gmail.com'
EMAIL_HOST_PASSWORD = 'tyjpqertlkccpuhw' #past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'Bookwallah HR team <bookwallahhr@gmail.com>'
DEFAULT_PASSWORD = 'bookwallah@123'

INSTALLED_APPS = [
    'django_celery_beat',
    'channels',
    'chat',
    'main',
    'django_admin_search',
    'django_mysql',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Bookwallah.urls'
OPTIMIZED_IMAGE_METHOD = 'pillow'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bookwallah.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'BW',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost'
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'bw',
#        'USER': 'bookwallah',
#        'PASSWORD': 'B00kwallah@123',
#        'HOST': 'localhost'
#    }
#}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

DATE_FORMAT = '%d-%m-%Y'
DATETIME_FORMAT = '%d-%m-%Y %H:%M:%S'

DATE_INPUT_FORMATS = [
    '%d-%m-%Y'
]

DATETIME_INPUT_FORMATS = [
    '%d-%m-%Y %H:%M:%S'
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_TZ = False


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "main", "static"),
    os.path.join(BASE_DIR, "chat", "static"),
]

MEDIAFILES_DIRS = [
    os.path.join(BASE_DIR, "media"),
]

LOGIN_URL = "/accounts/signin"

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
LOGIN_REDIRECT_URL = '/accounts/profile'
LOGOUT_REDIRECT_URL = '/accounts/signin'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'America/Chicago'

CELERY_BEAT_SCHEDULE = {
    'fetch_data': {
        'task': 'main.tasks.fetch_data',
        'schedule': crontab(minute=1, hour=0),
    },
    'purge_sheet': {
        'task': 'main.tasks.purge_sheet',
        'schedule': crontab(1, 0, day_of_month='1'),
    }
}