# Generated by Django 3.0.6 on 2020-07-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('main', '0002_remove_profile_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_room', to='chat.Room'),
        ),
    ]
