# Generated by Django 3.0.6 on 2020-07-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room'),
        ('main', '0004_auto_20200710_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_room', to='chat.Room'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
