# Generated by Django 3.0.6 on 2020-07-30 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200726_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='gallery',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='donor',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Involvement'),
        ),
        migrations.AddField(
            model_name='kid',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joining Date'),
        ),
    ]
