# Generated by Django 3.0.6 on 2020-07-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200730_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='date1',
        ),
    ]
