# Generated by Django 3.0.6 on 2020-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200730_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('East', 'East'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter (NPS Score)')),
                ('month', models.CharField(blank=True, choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=10, null=True, verbose_name='Month (NPS Score)')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Year (NPS Score)')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='Score (%) (NPS Score)')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='date1',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
