# Generated by Django 3.0.6 on 2020-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200731_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter (NPS Score)'),
        ),
    ]
