# Generated by Django 3.0.6 on 2020-07-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200731_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='empathy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Empathy Score (%) (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='hope',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hope Score (%) (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='perseverance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Perseverance Score (%) (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='pro_social_conduct',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pro Social Conduct Score (%) (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter (NPS Score)'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score (%) (NPS Score)'),
        ),
    ]
