# Generated by Django 3.0.6 on 2020-08-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200731_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childpsychologyscore',
            name='month',
        ),
        migrations.AddField(
            model_name='childpsychologyscore',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10, null=True, verbose_name='Quarter (NPS Score)'),
        ),
    ]
