# Generated by Django 3.0.6 on 2020-08-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200801_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10, null=True, verbose_name='Quarter (Child Psychology)'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter (NPS Score)'),
        ),
    ]
