# Generated by Django 3.0.6 on 2020-08-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200801_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childpsychologyscore',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter (NPS Score)'),
        ),
    ]
