# Generated by Django 3.0.6 on 2020-08-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200801_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='empathy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Empathy Score (%)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='hope',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hope Score (%)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='perseverance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Perseverance Score (%)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='pro_social_conduct',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pro Social Conduct Score (%)'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_survey_project_name', to='main.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10, null=True, verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='childpsychologyscore',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10, null=True, verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score (%)'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='ProSocialBehaviorScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=10, null=True, verbose_name='Quarter')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Year')),
                ('control', models.IntegerField(blank=True, null=True, verbose_name='Control (New Children to Bookwallah)')),
                ('treatment', models.IntegerField(blank=True, null=True, verbose_name='Treatment (Children with Bookwallah)')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='social_behavior_project_name', to='main.Project', verbose_name='Project')),
            ],
        ),
    ]
