# Generated by Django 3.0.6 on 2020-08-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200801_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='prosocialbehaviorscore',
            name='control',
            field=models.FloatField(blank=True, null=True, verbose_name='Control (New Children to Bookwallah)'),
        ),
        migrations.AlterField(
            model_name='prosocialbehaviorscore',
            name='treatment',
            field=models.FloatField(blank=True, null=True, verbose_name='Treatment (Children with Bookwallah)'),
        ),
    ]
