# Generated by Django 3.0.6 on 2020-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200811_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Config',
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
