# Generated by Django 3.0.6 on 2020-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200811_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('tenure', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('prior_exp', models.CharField(blank=True, max_length=500, null=True)),
                ('library', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='column_names',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
