# Generated by Django 3.0.6 on 2020-08-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200816_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='column_names',
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
