# Generated by Django 3.0.6 on 2020-08-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200817_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
