# Generated by Django 3.0.6 on 2020-08-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200817_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='prior_exp_field',
            new_name='library',
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
