# Generated by Django 3.0.6 on 2020-08-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200817_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='library',
            new_name='library_field',
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
