# Generated by Django 3.0.6 on 2020-08-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200817_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='tenure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
