# Generated by Django 3.0.6 on 2020-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200818_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='library',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='prior_exp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
