# Generated by Django 3.0.6 on 2020-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200818_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
