# Generated by Django 3.0.6 on 2020-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200819_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In-Process', 'In-Process'), ('Approved', 'Approved')], default='Pending', max_length=50, null=True),
        ),
    ]
