# Generated by Django 3.0.6 on 2020-08-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_recruit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_for',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_for', to='main.Donor'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
