# Generated by Django 3.0.6 on 2020-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200821_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter')),
                ('h1', models.CharField(blank=True, max_length=1000, null=True)),
                ('h2', models.CharField(blank=True, max_length=1000, null=True)),
                ('h3', models.CharField(blank=True, max_length=1000, null=True)),
                ('h4', models.CharField(blank=True, max_length=1000, null=True)),
                ('h5', models.CharField(blank=True, max_length=1000, null=True)),
                ('h6', models.CharField(blank=True, max_length=1000, null=True)),
                ('h7', models.CharField(blank=True, max_length=1000, null=True)),
                ('h8', models.CharField(blank=True, max_length=1000, null=True)),
                ('h9', models.CharField(blank=True, max_length=1000, null=True)),
                ('h10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Project Supplies', 'Project Supplies'), ('Supplies', 'Supplies'), ('Training', 'Training'), ('Session', 'Session'), ('Bonding', 'Bonding'), ('Staff', 'Staff'), ('Transport', 'Transport'), ('Volunteers', 'Volunteers'), ('Staff', 'Staff'), ('Meals', 'Meals'), ('Volunteer', 'Volunteer'), ('Meals', 'Meals'), ('Telephone', 'Telephone'), ('Rewards', 'Rewards'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
