# Generated by Django 3.0.6 on 2020-08-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200829_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='attended_sessions',
        ),
        migrations.AddField(
            model_name='config',
            name='top_kid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Kid'),
        ),
        migrations.AddField(
            model_name='config',
            name='top_volunteer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__groups__name': 'Volunteer'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
