# Generated by Django 3.0.6 on 2020-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200830_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, unique=True, verbose_name='Chapter')),
                ('i1', models.CharField(blank=True, max_length=1000, null=True)),
                ('i2', models.CharField(blank=True, max_length=1000, null=True)),
                ('i3', models.CharField(blank=True, max_length=1000, null=True)),
                ('i4', models.CharField(blank=True, max_length=1000, null=True)),
                ('i5', models.CharField(blank=True, max_length=1000, null=True)),
                ('i6', models.CharField(blank=True, max_length=1000, null=True)),
                ('i7', models.CharField(blank=True, max_length=1000, null=True)),
                ('i8', models.CharField(blank=True, max_length=1000, null=True)),
                ('i9', models.CharField(blank=True, max_length=1000, null=True)),
                ('i10', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
