# Generated by Django 3.0.6 on 2020-09-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200916_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
