# Generated by Django 3.0.6 on 2020-09-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200916_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
