# Generated by Django 3.0.6 on 2020-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200916_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
