# Generated by Django 3.0.6 on 2020-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20200917_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
