# Generated by Django 3.0.6 on 2020-09-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20200917_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('East', 'East'), ('Karnataka', 'Karnataka')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('East', 'East'), ('Karnataka', 'Karnataka')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('East', 'East'), ('Karnataka', 'Karnataka')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
