# Generated by Django 3.0.6 on 2020-09-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20200918_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, choices=[('Volunteer', 'Volunteer'), ('Donor', 'Donor'), ('Child', 'Child')], max_length=50, null=True, unique=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Donor'),
        ),
    ]
