# Generated by Django 3.0.6 on 2020-09-18 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0055_auto_20200918_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='user',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial',
            new_name='donor_testimonial',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='volunteer',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'Volunteer'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='volunteer_testimonial',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('East', 'East')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('East', 'East')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Karnataka', 'Karnataka'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
