# Generated by Django 3.0.6 on 2020-09-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200918_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('East', 'East')], max_length=30, null=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='volunteer',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'Volunteer'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Profile'),
        ),
    ]
