# Generated by Django 3.0.6 on 2020-09-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200918_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_testimonial', models.TextField(blank=True, max_length=1000, null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer_Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_testimonial', models.TextField(blank=True, max_length=1000, null=True)),
                ('volunteer', models.ForeignKey(limit_choices_to={'user__groups__name': 'Volunteer'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
