# Generated by Django 3.0.6 on 2020-10-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200920_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='donor',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, unique=True, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='npsscore',
            name='chapter',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('East', 'East'), ('West Bengal', 'West Bengal')], max_length=30, null=True, verbose_name='Chapter'),
        ),
    ]
